/*
 * About.java
 *
 * Created on August 25, 2006, 6:06 AM
 */

/**
 *
 * @author  torpid
 */
public class About extends javax.swing.JFrame {
    
    /** Creates new form About */
    public About(JTetris parent) {
        initComponents();
        this.parent = parent;
        setResizable(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        mainLabel.setText("<html>\nJTetris.<br>\nCreated by Timothy Sanders<br>\n<br>\nLicensed under the XXXX<br>\n<br>\n2006<br>\n</html>");
        mainLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(mainLabel, java.awt.BorderLayout.CENTER);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        getContentPane().add(closeButton, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.hide();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    public void hide() {
        super.hide();
        parent.unSuspend();
    }
    
    public void show() {
        super.show();
        parent.suspend();
    }
    
    /** Exit the Application */    
    /**
     * @param args the command line arguments
     */    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables

    private JTetris parent;    
    
}
